Update Jenkinsfile3.txt

diff --git a/Jenkinsfile3.txt b/Jenkinsfile3.txt
--- a/Jenkinsfile3.txt
+++ b/Jenkinsfile3.txt
@@ -3,8 +3,8 @@ pipeline {
     stages {
         stage('Test') {
             steps {
-                echo 'Fail!'; exit 1
-              //    echo 'SUCCESS'
+              //  echo 'Fail!'; exit 1
+                  echo 'SUCCESS'
             }
         }
     }
